### ISSUE TITLE
dismiss后showinfo不显示?

### ISSUE THREAD

**Issue by Reeye1024** [saiwu-bigkoo/Android-SVProgressHUD#21]
@Override
    public void showLoading() {
        tips.showWithStatus("正在加载");
    }

    @Override
    public void dismissLoading() {
        if (tips.isShowing()) {
            tips.dismiss();
        }
    }

 @Override
    public void showError(String msg) {
        tips.showErrorWithStatus(msg);
    }

方法从上到下执行, dimiss后 showError, showInfo什么的都没出现 1.0.6

**Comment by Reeye1024** [comment]
tips.dismissImmediately();

**Comment by Reeye1024** [comment]
原来要这样写啊....好吧...

**Comment by FlogFly** [comment]
我也看到这个了。但是那Dismiss又要用在什么情况下呢？
